### PR TITLE
ShA/feature controllers

### PR DESCRIPTION
**Pull request by AlekseiiShevchuk**
Base CommentController done

### CODE REVIEW

**Comment by binaryvo** [comment]
1. The method isCommentBelongsToVoteItem() better to declare as protected
2. if($voteWhichHasThisComment && $voteWhichHasThisComment->id === $vote->id){
           return true;
       }
      return false;
   probably would be more correctly:
   return ($voteWhichHasThisComment && $voteWhichHasThisComment->id === $vote->id)

**Comment by AlekseiiShevchuk** [comment]
Done

**Comment by binaryvo** [comment]
Take a look please. I guess that we can group some of routes with prefix https://laravel.com/docs/5.2/routing#route-group-prefixes

**Comment by AlekseiiShevchuk** [comment]
Done
Now, routs became a bit smaller :-)

**Pull request merged**
