### PR TITLE
Ssh/features vote stop

### PR DESCRIPTION
**Pull request by binaryshmelev**

### CODE REVIEW

**Comment by binaryshmelev** [comment]
In this PR also was fixed the bug with "Admin can't edit vote" by removing validation rules "is_curent_user", because this is do not need anymore, we use policy

**Comment by binaryvo** [comment]
Please update your branch from next, resolve conflicts and re-open PR

**Comment by binaryvo** [comment]
1. Button 'Stop Vote' should be visible for Vote Creator and for Admin;
2. The field 'finished_at' doesn't updating after vote stop action;
3. Move button 'Stop Vote' to actions panel before 'Edit', 'Answer' and so on. And make it as link, set text color - red.

**Comment by binaryshmelev** [comment]
Trying number...i don't remember the number of attempts) I am a small bee )))

**Pull request merged**
