### PR TITLE
Feature design part#1

### PR DESCRIPTION
**Pull request by skopa**
need review and test (dont changed topic detail, vote detail and messages)

### CODE REVIEW

**Comment by binaryvo** [comment]
Awesome! I like new design so much.

And now some remarks:

Topics: 
- Change vertical align of button 'Create Topic'. Make the same top and bottom margins;
- Move list icon from the link tag. Place will be the same;
- Move topic category title a bit above.

Thanks

**Comment by binaryvo** [comment]
Please hide button for comment replies if there is no comments presented 
selection_045

**Comment by binaryvo** [comment]
Please fix remarks, resolve conflicts and re-open PR

**Comment by skopa** [comment]
fixed, test please)

**Pull request merged**
